insert into User (UserID, Name, Email, Password)
values (1, 'Alice Smith', 'alice@iotbay.com', 'password1'),
       (2, 'Bob Johnson', 'bob@iotbay.com', 'password2'),
       (3, 'Carol Williams', 'carol@iotbay.com', 'password3'),
       (4, 'David Brown', 'david@iotbay.com', 'password4'),
       (5, 'Eve Davis', 'eve@iotbay.com', 'password5'),
       (6, 'Frank Miller', 'frank@iotbay.com', 'password6'),
       (7, 'Grace Wilson', 'grace@iotbay.com', 'password7'),
       (8, 'Henry Moore', 'henry@iotbay.com', 'password8'),
       (9, 'Ivy Taylor', 'ivy@iotbay.com', 'password9'),
       (10, 'Jack Anderson', 'jack@iotbay.com', 'password10'),
       (11, 'Karen Lee', 'karen@iotbay.com', 'password11'),
       (12, 'Liam Harris', 'liam@iotbay.com', 'password12'),
       (13, 'Mia Clark', 'mia@iotbay.com', 'password13'),
       (14, 'Noah Lewis', 'noah@iotbay.com', 'password14'),
       (15, 'Olivia Walker', 'olivia@iotbay.com', 'password15'),
       (16, 'Paul Young', 'paul@iotbay.com', 'password16'),
       (17, 'Quinn Hall', 'quinn@iotbay.com', 'password17'),
       (18, 'Ruby Allen', 'ruby@iotbay.com', 'password18'),
       (19, 'Sam King', 'sam@iotbay.com', 'password19'),
       (20, 'Tina Scott', 'tina@iotbay.com', 'password20');