insert into User (UserID, Name, Email, Password)
values (1, 'Alice Smith', 'alice@example.com', 'password1'),
       (2, 'Bob Johnson', 'bob@example.com', 'password2'),
       (3, 'Carol Williams', 'carol@example.com', 'password3'),
       (4, 'David Brown', 'david@example.com', 'password4'),
       (5, 'Eve Davis', 'eve@example.com', 'password5'),
       (6, 'Frank Miller', 'frank@example.com', 'password6'),
       (7, 'Grace Wilson', 'grace@example.com', 'password7'),
       (8, 'Henry Moore', 'henry@example.com', 'password8'),
       (9, 'Ivy Taylor', 'ivy@example.com', 'password9'),
       (10, 'Jack Anderson', 'jack@example.com', 'password10'),
       (11, 'Karen Lee', 'karen@example.com', 'password11'),
       (12, 'Liam Harris', 'liam@example.com', 'password12'),
       (13, 'Mia Clark', 'mia@example.com', 'password13'),
       (14, 'Noah Lewis', 'noah@example.com', 'password14'),
       (15, 'Olivia Walker', 'olivia@example.com', 'password15'),
       (16, 'Paul Young', 'paul@example.com', 'password16'),
       (17, 'Quinn Hall', 'quinn@example.com', 'password17'),
       (18, 'Ruby Allen', 'ruby@example.com', 'password18'),
       (19, 'Sam King', 'sam@example.com', 'password19'),
       (20, 'Tina Scott', 'tina@example.com', 'password20');