INSERT INTO Log (LogID, UserID, LogMessage)
VALUES (1, 1, 'User logged in'),
       (2, 2, 'User logged out'),
       (3, 3, 'User updated profile'),
       (4, 4, 'User changed password'),
       (5, 5, 'User added item to cart'),
       (6, 6, 'User removed item from cart'),
       (7, 7, 'User placed an order'),
       (8, 8, 'User cancelled an order'),
       (9, 9, 'User left a review'),
       (10, 10, 'User contacted support'),
       (11, 11, 'User updated shipping address'),
       (12, 12, 'User viewed order history'),
       (13, 13, 'User reset password'),
       (14, 14, 'User updated payment method'),
       (15, 15, 'User subscribed to newsletter'),
       (16, 16, 'User unsubscribed from newsletter'),
       (17, 17, 'User requested refund'),
       (18, 18, 'User account deactivated'),
       (19, 19, 'User account reactivated'),
       (20, 20, 'User updated notification settings');